baseurl = "https://blog.hungcq.xyz"
title = "Essays | HungCQ"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
hardWraps = false


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
author = "HungCQ"
info = "A Skeptic"
description = "HungCQ | Essays"
keywords = "blog,skepticism,software-engineering"
#avatarurl = "images/avatar.jpg"
gravatar = "hungcqrt@gmail.com"

faviconSVG = "/images/my-face-square.jpg"
favicon_32 = "/images/my-face-square.jpg"
favicon_16 = "/images/my-face-square.jpg"

since = 2022

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/hungcq"
[[params.social]]
name = "goodreads"
icon = "fa-brands fa-goodreads fa-2x"
weight = 3
url = "https://www.goodreads.com/user/show/118617249-hung-chu"

# Menu links
[[menu.main]]
name = "Home"
weight = 1
url  = "/"
[[menu.main]]
name = "All Posts"
weight = 2
url  = "/posts"
[[menu.main]]
name = "Essays"
weight = 3
url  = "categories/essays/"
[[menu.main]]
name = "Poems"
weight = 4
url  = "categories/poems/"
[[menu.main]]
name = "In English"
weight = 5
url  = "categories/english/"
[[menu.main]]
name = "In Vietnamese"
weight = 6
url  = "categories/vietnamese/"
#[[menu.main]]
#name = "About"
#weight = 2
#url = "about/"